name: focus
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^3.0.2
  cupertino_icons: ^0.1.2
  edge_alert: ^0.0.1
  email_validator: null
  flutter_statusbarcolor: ^0.2.3
  flutter_plugin_android_lifecycle: ^2.0.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.1
  http: ^0.13.0
  image_cropper: ^1.2.0
  image_picker: ^0.7.2
  image_picker_platform_interface: ^2.0.0
  intl: ^0.17.0
  local_auth: ^1.1.0
  location: ^4.1.1
  path_provider: ^2.0.0
  rflutter_alert: ^1.1.0
  shared_preferences: ^2.0.4
  table_calendar: ^2.3.0
  url_launcher: ^6.0.2 
  geolocator: ^7.0.1
  onesignal_flutter: ^2.6.3
  whatsapp_unilink: ^1.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/logo_home.png
    - images/key.png
    - images/logo.png
    - images/tela.jpg
    - images/semregistro.png
    - images/iconmap.png
    - images/mapa.json
  